### ISSUE TITLE
Mysql install error

### ISSUE THREAD

**Issue by mlwilkerson** [SenteraLLC/graphql-subscriptions-spike#1]
Thank you for making this demo! It's helpful already to read through the code. I hope to be able to run it as well.

I'm following the instructions in the README for building the rails server and when I do the second step:
`docker-compose run rails rake db:create db:setup RAILS_ENV=development`
I get this failure:

```
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>false, "database"=>"graphql_subscriptions_development", "pool"=>5, "username"=>"root", "password"=>"root", "host"=>"mysql"}
rake aborted!
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:185:in `spec'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:58:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/mysql_database_tasks.rb:6:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/mysql_database_tasks.rb:13:in `create'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:117:in `create'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Gem::LoadError: can't activate mysql2 (< 0.5, >= 0.3.18), already activated mysql2-0.5.0. Make sure all dependencies are added to Gemfile.
/usr/local/rvm/gems/ruby-2.4.3@global/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/mysql2_adapter.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:186:in `spec'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:58:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/mysql_database_tasks.rb:6:in `establish_connection'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/mysql_database_tasks.rb:13:in `create'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:117:in `create'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
/usr/local/rvm/gems/ruby-2.4.3/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create
```

**Comment by mlwilkerson** [comment]
I worked around this issue for the moment by locking the `mysql2` gem version in `Gemfile`:
```
gem 'mysql2', '0.4.1'
```
and rebuilding

**Comment by cebartling** [comment]
@mlwilkerson I'll lock the `mysql2` gem in the spike solution so others don't hit this same issue. Thanks for reporting this.
